name: Nodejs CI
on:
  push:
    branches:
      - master
# on: push
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
      fail-fast:
        false
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: test leetcode
      run: cd leetcode && yarn --frozen-lockfile && yarn run test

    - name: build blogs
      if: ${{ matrix.node-version == '10.x' }}
      run: git config --global user.email "hylbegoat@gmail.com" && git config --global user.name "begoat" && cd blogs && yarn --frozen-lockfile && yarn run deploy
      # https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
      # we don't need manually create a developer token ourself because it generated automatically and will expire automatically
      env:
        GITHUB_PAT: ${{ secrets.GH_PAGE_TOKEN }}
